# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# extra files in ~/.zsh/configs/pre , ~/.zsh/configs , and ~/.zsh/configs/post
# these are loaded first, second, and third, respectively.
_load_settings() {
  _dir="$1"
  if [ -d "$_dir" ]; then
    if [ -d "$_dir/pre" ]; then
      for config in "$_dir"/pre/**/*~*.zwc(N-.); do
        . $config
      done
    fi

    for config in "$_dir"/**/*(N-.); do
      case "$config" in
        "$_dir"/(pre|post)/*|*.zwc)
          :
          ;;
        *)
          . $config
          ;;
      esac
    done

    if [ -d "$_dir/post" ]; then
      for config in "$_dir"/post/**/*~*.zwc(N-.); do
        . $config
      done
    fi
  fi
}
_load_settings "$HOME/.zsh/configs"

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# BEGIN PERSONAL

# In this file to ensure availability during setup
function in-shopify() {
  shopify_env_file=~/.shopify-env

  if test -f $shopify_env_file; then
    return 0
  else
    return 1
  fi
}

function in-personal() {
  return $(! in-shopify)
}

export NIX_SOURCE_DIR="$(nix-source-dir)"
export EDITOR="$(which nvim)"
export SHELL="$(which zsh)"

export PATH="/usr/sbin:$PATH"

# Add personal scripts to path
export PATH="$HOME/.scripts:$PATH"

# Tmuxinator shell completions
source ~/.zsh/etc/tmuxinator.zsh

# NVM config
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if in-personal; then
  source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
  source /opt/homebrew/opt/chruby/share/chruby/auto.sh

  chruby ruby 3
fi

