{
  config,
  pkgs,
  lib,
  ...
}:

{
  # Import the file-copy module
  imports = [ ../modules/file-copy.nix ];

  # Configure the file-copy module
  modules.fileCopy = {

    # Define files to copy after home-manager generation
    files = [
      {
        # Path to an original configuration file
        source = ../lib/zshrc;
        # Path where you want the writable copy
        destination = "/tmp/writable-zshrc";
      }
      {
        # You can also use config files generated by nix
        source = "${config.home.path}/etc/config.toml";
        destination = "/var/lib/app/config.toml";
      }
    ];
  };
}
