#!/usr/bin/ruby

require 'fileutils'

def execute
  directories = Dir.children('.')
    .filter {|f| File.directory?(f)}

  directories.each do |dir|
    files = Dir.children(dir)
      .reject {|f| File.directory?(f)}

    files.each do |file|
      FileUtils.mv(File.join(dir, file), file)
    end

    Dir.rmdir(dir)
  end
end

execute
